### ISSUE TITLE
Linking problem with LLVM libraries

### ISSUE THREAD

**Issue by ddcc** [secure-software-engineering/phasar#57]
On a Ubuntu 18.04 machine using Clang/LLVM provided by the package repositories (`sudo apt-get install libclang-8-dev`), I am able to build Phasar successfully (`LLVM_DIR=/usr/lib/llvm-8 CC=clang-8 CXX=clang++-8 cmake ..`), but get the following error at runtime:

```
./phasar
: CommandLine Error: Option 'verify-dom-info' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

It looks like the problem is that Phasar links statically against the LLVM components from the repository package, for each of Phasar's plugin libraries. I've managed to fix this locally with a hacky commit that forces shared linking, but an actual fix would probably need to check the build and set some variables/dependencies accordingly: https://github.com/ddcc/phasar/commit/7f6369874ff7840438d41aa74d897cbb2c2e5fd0

This doesn't seem to be an uncommon problem when linking with Clang/LLVM, here are some related discussions:
https://github.com/ziglang/zig/issues/67
https://github.com/AnyDSL/impala/issues/63
https://github.com/CastXML/CastXML/issues/102

**Comment by pdschubert** [comment]
Thanks for reporting the problem!
Yes, we are having some trouble when statically linking against LLVM. Linking dynamically against LLVM/the LLVM libraries circumvents the problem as you already figured. We will try to allocate some resources to clean up the library dependencies. For the moment, I will add an entry to Phasar's wiki page concerning known bugs.

**Comment by vulder** [comment]
I fixed a linking Problem with phasar_pass and phasar_db
@ddcc could you please check if this also resolves your issue?
If not I'll look into full static linking with a single LLVM target.

**Comment by ddcc** [comment]
I just tried the `FixSharedStaticLinking` branch, and it doesn't seem to be working:

```
[222/224] Linking CXX executable phasar
FAILED: phasar
: && /usr/bin/clang++-8  -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -march=native -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DPHASAR_PLUGINS_ENABLED -O2 -g -DNDEBUG  -rdynamic CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o  -o phasar  -Wl,-rpath,/mnt/data/sources/phasar/build2/lib/Controller:/mnt/data/sources/phasar/build2/lib/Experimental:/mnt/data/sources/phasar/build2/lib/PhasarClang:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/Plugins:/mnt/data/sources/phasar/build2/external/googletest/googlemock/gtest:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/IfdsIde:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/ControlFlow:/mnt/data/sources/phasar/build2/lib/DB:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/Passes:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/Pointer:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/Mono:/mnt/data/sources/phasar/build2/lib/Utils:/mnt/data/sources/phasar/build2/lib/Config:/mnt/data/sources/phasar/build2/lib/PhasarLLVM/Utils: lib/Controller/libphasar_controller.so lib/Experimental/libphasar_experimental.so lib/PhasarClang/libphasar_clang.so lib/PhasarLLVM/Plugins/libphasar_plugins.so -lboost_program_options -lboost_filesystem -lboost_graph -lboost_system -lboost_log -lboost_thread -lsqlite3 -lboost_filesystem -lboost_graph -lboost_system -lboost_program_options -lboost_log -lboost_thread -lboost_date_time -lboost_log_setup -lboost_regex -lboost_chrono -lboost_atomic -lpthread -ldl -pthread -lclangTooling -lclangFrontendTool -lclangFrontend -lclangDriver -lclangSerialization -lclangCodeGen -lclangParse -lclangSema -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangAnalysis -lclangARCMigrate -lclangRewrite -lclangRewriteFrontend -lclangEdit -lclangAST -lclangASTMatchers
-lclangLex -lclangBasic -lcurl external/googletest/googlemock/gtest/libgtest.so lib/PhasarLLVM/IfdsIde/libphasar_ifdside.so lib/PhasarLLVM/ControlFlow/libphasar_controlflow.so lib/DB/libphasar_db.so lib/PhasarLLVM/Passes/libphasar_passes.so /usr/lib/llvm-8/lib/libLLVMObjCARCOpts.a /usr/lib/llvm-8/lib/libLLVMCodeGen.a /usr/lib/llvm-8/lib/libLLVMTarget.a /usr/lib/llvm-8/lib/libLLVMipo.a /usr/lib/llvm-8/lib/libLLVMVectorize.a /usr/lib/llvm-8/lib/libLLVMScalarOpts.a /usr/lib/llvm-8/lib/libLLVMInstrumentation.a /usr/lib/llvm-8/lib/libLLVMAggressiveInstCombine.a /usr/lib/llvm-8/lib/libLLVMIRReader.a /usr/lib/llvm-8/lib/libLLVMAsmParser.a /usr/lib/llvm-8/lib/libLLVMInstCombine.a /usr/lib/llvm-8/lib/libLLVMLinker.a /usr/lib/llvm-8/lib/libLLVMTransformUtils.a lib/PhasarLLVM/Pointer/libphasar_pointer.so lib/PhasarLLVM/Mono/libphasar_mono.so lib/Utils/libphasar_utils.so lib/Config/libphasar_config.so /usr/lib/llvm-8/lib/libLLVMBitWriter.a /usr/lib/llvm-8/lib/libLLVMAnalysis.a /usr/lib/llvm-8/lib/libLLVMProfileData.a /usr/lib/llvm-8/lib/libLLVMObject.a /usr/lib/llvm-8/lib/libLLVMBitReader.a /usr/lib/llvm-8/lib/libLLVMMCParser.a /usr/lib/llvm-8/lib/libLLVMMC.a /usr/lib/llvm-8/lib/libLLVMDebugInfoCodeView.a /usr/lib/llvm-8/lib/libLLVMDebugInfoMSF.a lib/PhasarLLVM/Utils/libphasar_phasarllvm_utils.so /usr/lib/llvm-8/lib/libLLVMCore.a /usr/lib/llvm-8/lib/libLLVMBinaryFormat.a /usr/lib/llvm-8/lib/libLLVMSupport.a -lz -lrt -ltinfo -lm /usr/lib/llvm-8/lib/libLLVMDemangle.a -lboost_filesystem -lboost_system -lboost_log -lsqlite3 -lboost_filesystem -lboost_graph -lboost_system -lboost_program_options -lboost_log -lboost_thread -lboost_date_time -lboost_log_setup -lboost_regex -lboost_chrono -lboost_atomic -lpthread -ldl -lpthread && :
/usr/lib/llvm-8/bin/../lib/libclangTooling.a(CompilationDatabase.cpp.o): In function `clang::driver::Driver::~Driver()':
CompilationDatabase.cpp:(.text._ZN5clang6driver6DriverD2Ev[_ZN5clang6driver6DriverD2Ev]+0x40a): undefined reference to `llvm::opt::OptTable::~OptTable()'
/usr/lib/llvm-8/bin/../lib/libclangTooling.a(CompilationDatabase.cpp.o): In function `llvm::opt::InputArgList::~InputArgList()':
CompilationDatabase.cpp:(.text._ZN4llvm3opt12InputArgListD2Ev[_ZN4llvm3opt12InputArgListD2Ev]+0xe): undefined reference to `vtable for llvm::opt::InputArgList'
CompilationDatabase.cpp:(.text._ZN4llvm3opt12InputArgListD2Ev[_ZN4llvm3opt12InputArgListD2Ev]+0x1a): undefined reference to `llvm::opt::InputArgList::releaseMemory()'
/usr/lib/llvm-8/bin/../lib/libclangTooling.a(InterpolatingCompilationDatabase.cpp.o): In function `clang::tooling::(anonymous namespace)::InterpolatingCompilationDatabase::getCompileCommands(llvm::StringRef) const':
InterpolatingCompilationDatabase.cpp:(.text._ZNK5clang7tooling12_GLOBAL__N_132InterpolatingCompilationDatabase18getCompileCommandsEN4llvm9StringRefE+0xe80): undefined reference to `vtable for llvm::opt::InputArgList'
InterpolatingCompilationDatabase.cpp:(.text._ZNK5clang7tooling12_GLOBAL__N_132InterpolatingCompilationDatabase18getCompileCommandsEN4llvm9StringRefE+0xf95): undefined reference to `llvm::opt::InputArgList::InputArgList(char const* const*, char const* const*)'
InterpolatingCompilationDatabase.cpp:(.text._ZNK5clang7tooling12_GLOBAL__N_132InterpolatingCompilationDatabase18getCompileCommandsEN4llvm9StringRefE+0x1165): undefined reference to `llvm::opt::OptTable::ParseOneArg(llvm::opt::ArgList
const&, unsigned int&, unsigned int, unsigned int) const'
InterpolatingCompilationDatabase.cpp:(.text._ZNK5clang7tooling12_GLOBAL__N_132InterpolatingCompilationDatabase18getCompileCommandsEN4llvm9StringRefE+0x117e): undefined reference to `llvm::opt::Option::matches(llvm::opt::OptSpecifier)
...
```

**Comment by pdschubert** [comment]
We reworked phasar linking a bit, changes are on the development branch. It fixed a lot on our systems. Could you please try if it works for you now?

**Comment by ddcc** [comment]
Hmm, now I just get a lot of compiler errors about `bfs` being ambiguous:


```
[58/160] Building CXX object CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o
FAILED: CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o
/usr/bin/c++  -DBOOST_LOG_DYN_LINK -I../include -I../external/json/single_include/nlohmann -I../external/googletest/googletest/include -I../external/googletest/googlemock/include -I../external/WALi-OpenNWA/Source/wali/include -I../external/wise_enum -I/usr/lib/llvm-9/include -MP -fvisibility-inlines-hidden -fstack-protector-strong -ffunction-sections -fdata-sections -pipe -g -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-return-type-c-linkage  -fPIC -DPHASAR_PLUGINS_ENABLED -g   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++1z -MD -MT CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o -MF CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o.d -o CMakeFiles/phasar.dir/tools/phasar/phasar.cpp.o -c ../tools/phasar/phasar.cpp
../tools/phasar/phasar.cpp: In function ‘void validateParamModule(const std::vector<std::__cxx11::basic_string<char>
>&)’:
../tools/phasar/phasar.cpp:62:11: error: reference to ‘bfs’ is ambiguous
     if (!(bfs::exists(module) && !bfs::is_directory(module))) {
           ^~~
../tools/phasar/phasar.cpp:40:34: note: candidates are: namespace bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
In file included from ../tools/phasar/phasar.cpp:36:0:
../include/phasar/Utils/Logger.h:33:34: note:                 namespace psr::bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
../tools/phasar/phasar.cpp:62:35: error: reference to ‘bfs’ is ambiguous
     if (!(bfs::exists(module) && !bfs::is_directory(module))) {
                                   ^~~
../tools/phasar/phasar.cpp:40:34: note: candidates are: namespace bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
In file included from ../tools/phasar/phasar.cpp:36:0:
../include/phasar/Utils/Logger.h:33:34: note:                 namespace psr::bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
../tools/phasar/phasar.cpp: In function ‘void validateParamProject(const string&)’:
../tools/phasar/phasar.cpp:70:9: error: reference to ‘bfs’ is ambiguous
   if (!(bfs::exists(project) && bfs::is_directory(project) &&
         ^~~
../tools/phasar/phasar.cpp:40:34: note: candidates are: namespace bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
In file included from ../tools/phasar/phasar.cpp:36:0:
../include/phasar/Utils/Logger.h:33:34: note:                 namespace psr::bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
../tools/phasar/phasar.cpp:70:33: error: reference to ‘bfs’ is ambiguous
   if (!(bfs::exists(project) && bfs::is_directory(project) &&
                                 ^~~
../tools/phasar/phasar.cpp:40:34: note: candidates are: namespace bfs = boost::boost::filesystem;
 namespace bfs = boost::filesystem;
                                  ^
```

**Comment by pdschubert** [comment]
Should be fixed by now. Please check the development branch.

**Comment by ddcc** [comment]
Hmm, that error has gone away, but the original issue still remains:

```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I'm using the llvm-9 packages from apt.llvm.org:
```
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
```

**Comment by kejane** [comment]
I meet the same problem on master branch when I'm trying to install it on Ubuntu 18.04 and LLVM8.0.1.

`ubuntu@llvm1804:~/phasar$ sudo phasar --module test/build_systems_tests/installation_tests/module.ll -D IFDS_SolverTest
phasar: error while loading shared libraries: libphasar_controller.so: cannot open shared object file: No such file or directory`

**Comment by kejane** [comment]
Everything seems normally if run it on ubuntu  18.04 using the bootstrap.sh.

but we need to install some boost library.

`
sudo apt-get install libboost-thread-dev
sudo apt install libboost-program-options-dev
sudo apt-get install libboost-filesystem-dev
sudo apt-get install libboost-graph-dev
sudo apt-get install libboost-system-dev
`

**Comment by kejane** [comment]
Everything works well if we don't use the  llvm packages from apt.llvm.org in ubuntu 18.04, but I don't know why.

**Comment by MMory** [comment]
Do you still have the issue when building the current state of the development branch?

**Comment by bsauce** [comment]
> Do you still have the issue when building the current state of the development branch?

I still have the same issue in ubuntu 18.04.
